// Build the widget bundle, wrapped in a page-level module cache.
//
// anywidget evaluates a widget's `_esm` text once PER MODEL (each model gets
// its own blob URL), so a notebook with N figures would otherwise parse and
// evaluate N copies of this bundle — and N copies of three.js, which warns
// "Multiple instances of Three.js being imported" on every one after the
// first. The shipped file is therefore a tiny loader stub: the real bundle
// is embedded as a string, imported through a blob URL exactly once per page
// keyed by content hash on globalThis, and every model shares that module.
// The hash key lets two different anythreejs versions coexist on one page.
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";

import { build } from "esbuild";

const OUTFILE = "src/anythreejs/static/widget.js";

const result = await build({
  entryPoints: ["js/widget.js"],
  bundle: true,
  format: "esm",
  minify: true,
  write: false,
  outfile: OUTFILE,
});

const code = result.outputFiles[0].text;
const hash = createHash("sha256").update(code).digest("hex").slice(0, 16);

const stub = `// anythreejs widget bundle (generated by build.mjs — do not edit).
// Loader stub: the real module is embedded below and evaluated once per
// page via a globalThis cache, shared by every widget model.
const KEY = "__anythreejs_esm_${hash}";
if (!globalThis[KEY]) {
  const src = ${JSON.stringify(code)};
  const url = URL.createObjectURL(new Blob([src], { type: "text/javascript" }));
  globalThis[KEY] = import(url).finally(() => URL.revokeObjectURL(url));
}
const mod = await globalThis[KEY];
export default mod.default;
`;

writeFileSync(OUTFILE, stub);
console.log(`wrote ${OUTFILE} (${(stub.length / 1024).toFixed(0)}KB, key ${hash})`);
