"""Generated by scripts/generate_stubs.py — do not edit."""

from collections.abc import Sequence
from typing import Any

from .base import ThreeJSBase

class OrbitControls(ThreeJSBase):
    controlling: Any
    @property
    def target(self) -> tuple[float, ...]: ...
    @target.setter
    def target(self, value: Sequence[float]) -> None: ...
    enableDamping: bool
    dampingFactor: float
    enableZoom: bool
    enableRotate: bool
    enablePan: bool
    autoRotate: bool
    autoRotateSpeed: float
    screenSpacePanning: bool
    def __init__(
        self,
        controlling: Any = ...,
        target: Sequence[float] = ...,
        enableDamping: bool = ...,
        dampingFactor: float = ...,
        enableZoom: bool = ...,
        enableRotate: bool = ...,
        enablePan: bool = ...,
        autoRotate: bool = ...,
        autoRotateSpeed: float = ...,
        screenSpacePanning: bool = ...,
        **kwargs: Any,
    ) -> None: ...

class TrackballControls(ThreeJSBase):
    controlling: Any
    @property
    def target(self) -> tuple[float, ...]: ...
    @target.setter
    def target(self, value: Sequence[float]) -> None: ...
    def __init__(
        self, controlling: Any = ..., target: Sequence[float] = ..., **kwargs: Any
    ) -> None: ...

class Picker(ThreeJSBase):
    controlling: Any
    event: Any
    all: Any
    lineThreshold: Any
    pointThreshold: Any
    point: Any
    face: Any
    faceNormal: Any
    faceIndex: Any
    object: Any
    distance: Any
    modifiers: Any
    def __init__(
        self,
        controlling: Any = ...,
        event: Any = ...,
        all: Any = ...,
        lineThreshold: Any = ...,
        pointThreshold: Any = ...,
        **kwargs: Any,
    ) -> None: ...
