"""Generated by scripts/generate_stubs.py — do not edit."""

from typing import Any

from .base import ThreeJSBase

class BufferGeometry(ThreeJSBase):
    attributes: Any
    index: Any
    def __init__(
        self, attributes: Any = ..., index: Any = ..., **kwargs: Any
    ) -> None: ...

class BoxGeometry(ThreeJSBase):
    width: float
    height: float
    depth: float
    widthSegments: int
    heightSegments: int
    depthSegments: int
    def __init__(
        self,
        width: float = ...,
        height: float = ...,
        depth: float = ...,
        widthSegments: int = ...,
        heightSegments: int = ...,
        depthSegments: int = ...,
        **kwargs: Any,
    ) -> None: ...

class SphereGeometry(ThreeJSBase):
    radius: float
    widthSegments: int
    heightSegments: int
    phiStart: float
    phiLength: float
    thetaStart: float
    thetaLength: float
    def __init__(
        self,
        radius: float = ...,
        widthSegments: int = ...,
        heightSegments: int = ...,
        phiStart: float = ...,
        phiLength: float = ...,
        thetaStart: float = ...,
        thetaLength: float = ...,
        **kwargs: Any,
    ) -> None: ...

class PlaneGeometry(ThreeJSBase):
    width: float
    height: float
    widthSegments: int
    heightSegments: int
    def __init__(
        self,
        width: float = ...,
        height: float = ...,
        widthSegments: int = ...,
        heightSegments: int = ...,
        **kwargs: Any,
    ) -> None: ...

class CylinderGeometry(ThreeJSBase):
    radiusTop: float
    radiusBottom: float
    height: float
    radialSegments: int
    heightSegments: int
    openEnded: bool
    thetaStart: float
    thetaLength: float
    def __init__(
        self,
        radiusTop: float = ...,
        radiusBottom: float = ...,
        height: float = ...,
        radialSegments: int = ...,
        heightSegments: int = ...,
        openEnded: bool = ...,
        thetaStart: float = ...,
        thetaLength: float = ...,
        **kwargs: Any,
    ) -> None: ...

class TorusGeometry(ThreeJSBase):
    radius: float
    tube: float
    radialSegments: int
    tubularSegments: int
    arc: float
    def __init__(
        self,
        radius: float = ...,
        tube: float = ...,
        radialSegments: int = ...,
        tubularSegments: int = ...,
        arc: float = ...,
        **kwargs: Any,
    ) -> None: ...

class EdgesGeometry(ThreeJSBase):
    geometry: Any
    thresholdAngle: Any
    def __init__(
        self, geometry: Any = ..., thresholdAngle: Any = ..., **kwargs: Any
    ) -> None: ...

class LineGeometry(ThreeJSBase):
    positions: Any
    colors: Any
    def __init__(
        self, positions: Any = ..., colors: Any = ..., **kwargs: Any
    ) -> None: ...

BoxBufferGeometry = BoxGeometry
SphereBufferGeometry = SphereGeometry
PlaneBufferGeometry = PlaneGeometry
CylinderBufferGeometry = CylinderGeometry
