"""Generated by scripts/generate_stubs.py — do not edit."""

from typing import Any

from .base import Object3D

class AxesHelper(Object3D):
    size: float
    def __init__(self, size: float = ..., **kwargs: Any) -> None: ...

class GridHelper(Object3D):
    size: float
    divisions: float
    colorCenterLine: str
    colorGrid: str
    def __init__(
        self,
        size: float = ...,
        divisions: float = ...,
        colorCenterLine: str = ...,
        colorGrid: str = ...,
        **kwargs: Any,
    ) -> None: ...
