"""Generated by scripts/generate_stubs.py — do not edit."""

from collections.abc import Sequence
from typing import Any

from .base import Object3D

class AmbientLight(Object3D):
    color: str
    intensity: float
    def __init__(
        self, color: str = ..., intensity: float = ..., **kwargs: Any
    ) -> None: ...

class DirectionalLight(Object3D):
    color: str
    intensity: float
    castShadow: bool
    @property
    def target(self) -> tuple[float, ...]: ...
    @target.setter
    def target(self, value: Sequence[float]) -> None: ...
    def __init__(
        self,
        color: str = ...,
        intensity: float = ...,
        castShadow: bool = ...,
        target: Sequence[float] = ...,
        **kwargs: Any,
    ) -> None: ...

class PointLight(Object3D):
    color: str
    intensity: float
    distance: float
    decay: float
    castShadow: bool
    def __init__(
        self,
        color: str = ...,
        intensity: float = ...,
        distance: float = ...,
        decay: float = ...,
        castShadow: bool = ...,
        **kwargs: Any,
    ) -> None: ...

class HemisphereLight(Object3D):
    skyColor: str
    groundColor: str
    intensity: float
    def __init__(
        self,
        skyColor: str = ...,
        groundColor: str = ...,
        intensity: float = ...,
        **kwargs: Any,
    ) -> None: ...

class SpotLight(Object3D):
    color: str
    intensity: float
    distance: float
    angle: float
    penumbra: float
    decay: float
    castShadow: bool
    @property
    def target(self) -> tuple[float, ...]: ...
    @target.setter
    def target(self, value: Sequence[float]) -> None: ...
    def __init__(
        self,
        color: str = ...,
        intensity: float = ...,
        distance: float = ...,
        angle: float = ...,
        penumbra: float = ...,
        decay: float = ...,
        castShadow: bool = ...,
        target: Sequence[float] = ...,
        **kwargs: Any,
    ) -> None: ...
