"""Generated by scripts/generate_stubs.py — do not edit."""

from collections.abc import Sequence
from typing import Any

from .base import ThreeJSBase

SIDE_MAP: dict[str, str]

class Material(ThreeJSBase):
    color: str
    opacity: float
    transparent: bool
    visible: bool
    side: str
    depthTest: bool
    depthWrite: bool
    def __init__(
        self,
        color: str = ...,
        opacity: float = ...,
        transparent: bool = ...,
        visible: bool = ...,
        side: str = ...,
        depthTest: bool = ...,
        depthWrite: bool = ...,
        **kwargs: Any,
    ) -> None: ...

class MeshBasicMaterial(Material):
    wireframe: bool
    vertexColors: bool | str
    map: Any
    def __init__(
        self,
        wireframe: bool = ...,
        vertexColors: bool | str = ...,
        map: Any = ...,
        **kwargs: Any,
    ) -> None: ...

class MeshStandardMaterial(Material):
    roughness: float
    metalness: float
    wireframe: bool
    flatShading: bool
    vertexColors: bool | str
    emissive: str
    emissiveIntensity: float
    def __init__(
        self,
        roughness: float = ...,
        metalness: float = ...,
        wireframe: bool = ...,
        flatShading: bool = ...,
        vertexColors: bool | str = ...,
        emissive: str = ...,
        emissiveIntensity: float = ...,
        **kwargs: Any,
    ) -> None: ...

class MeshPhongMaterial(Material):
    shininess: float
    specular: str
    wireframe: bool
    flatShading: bool
    vertexColors: bool | str
    def __init__(
        self,
        shininess: float = ...,
        specular: str = ...,
        wireframe: bool = ...,
        flatShading: bool = ...,
        vertexColors: bool | str = ...,
        **kwargs: Any,
    ) -> None: ...

class MeshLambertMaterial(Material):
    wireframe: bool
    vertexColors: bool | str
    def __init__(
        self, wireframe: bool = ..., vertexColors: bool | str = ..., **kwargs: Any
    ) -> None: ...

class PointsMaterial(Material):
    size: float
    sizeAttenuation: bool
    vertexColors: bool | str
    def __init__(
        self,
        size: float = ...,
        sizeAttenuation: bool = ...,
        vertexColors: bool | str = ...,
        **kwargs: Any,
    ) -> None: ...

class LineBasicMaterial(Material):
    linewidth: float
    vertexColors: bool | str
    def __init__(
        self, linewidth: float = ..., vertexColors: bool | str = ..., **kwargs: Any
    ) -> None: ...

class LineDashedMaterial(LineBasicMaterial):
    dashSize: float
    gapSize: float
    def __init__(
        self, dashSize: float = ..., gapSize: float = ..., **kwargs: Any
    ) -> None: ...

class SpriteMaterial(ThreeJSBase):
    map: Any
    color: str
    opacity: float
    transparent: bool
    def __init__(
        self,
        map: Any = ...,
        color: str = ...,
        opacity: float = ...,
        transparent: bool = ...,
        **kwargs: Any,
    ) -> None: ...

class LineMaterial(ThreeJSBase):
    color: str
    linewidth: float
    opacity: float
    transparent: bool
    dashed: bool
    dashScale: float
    dashSize: float
    gapSize: float
    vertexColors: bool | str
    @property
    def resolution(self) -> tuple[float, ...] | None: ...
    @resolution.setter
    def resolution(self, value: Sequence[float] | None) -> None: ...
    def __init__(
        self,
        color: str = ...,
        linewidth: float = ...,
        opacity: float = ...,
        transparent: bool = ...,
        dashed: bool = ...,
        dashScale: float = ...,
        dashSize: float = ...,
        gapSize: float = ...,
        vertexColors: bool | str = ...,
        resolution: Sequence[float] | None = ...,
        **kwargs: Any,
    ) -> None: ...

class ShaderMaterial(ThreeJSBase):
    uniforms: Any
    vertexShader: Any
    fragmentShader: Any
    transparent: bool
    opacity: float
    visible: bool
    side: str
    depthTest: bool
    depthWrite: bool
    def __init__(
        self,
        uniforms: Any = ...,
        vertexShader: Any = ...,
        fragmentShader: Any = ...,
        transparent: bool = ...,
        opacity: float = ...,
        visible: bool = ...,
        side: str = ...,
        depthTest: bool = ...,
        depthWrite: bool = ...,
        **kwargs: Any,
    ) -> None: ...
