"""Generated by scripts/generate_stubs.py — do not edit."""

from typing import Any

from .base import ThreeJSBase

class TextTexture(ThreeJSBase):
    string: str
    color: str
    size: float
    fontFace: str
    squareTexture: bool
    def __init__(
        self,
        string: str = ...,
        color: str = ...,
        size: float = ...,
        fontFace: str = ...,
        squareTexture: bool = ...,
        **kwargs: Any,
    ) -> None: ...

class DataTexture(ThreeJSBase):
    data: Any
    width: Any
    height: Any
    def __init__(
        self,
        data: Any = ...,
        width: Any = ...,
        height: Any = ...,
        format: Any = ...,
        type: Any = ...,
        mapping: Any = ...,
        wrapS: Any = ...,
        wrapT: Any = ...,
        magFilter: Any = ...,
        minFilter: Any = ...,
        **kwargs: Any,
    ) -> None: ...
