"""Generate .pyi stubs for modules whose classes come from the declarative
catalog (core/spec.py), so IDEs and type checkers see real constructor
signatures and fields for the dynamically generated classes.

Hand-written classes living in the same modules are introspected too — a
.pyi shadows its whole module, so each stub must be complete.

Run:  uv run python scripts/generate_stubs.py
CI regenerates and diffs the committed stubs (like the JS bundle).
"""

import inspect
import subprocess
import sys
from pathlib import Path

from anythreejs.core import controls, geometry, helpers, lights, material, textures
from anythreejs.core.spec import CATALOG

MODULES = [material, lights, helpers, controls, geometry, textures]
CORE_DIR = Path(__file__).resolve().parent.parent / "src" / "anythreejs" / "core"


def field_annotation(name, field):
    kind = field.get("kind", "value")
    if kind in ("ref", "ref_unowned"):
        return "Any"
    if kind in ("color", "css", "side"):
        return "str"
    if name == "vertexColors":
        return "bool | str"  # pythreejs compat: accepts 'VertexColors'
    default = field.get("default")
    if isinstance(default, bool):
        return "bool"
    validate = field.get("validate")
    if validate and validate[0] == "min_int":
        return "int"
    if isinstance(default, (int, float)):
        return "float"
    if isinstance(default, str):
        return "str"
    return "Any"


def emit_catalog_class(name, cls):
    base = cls.__mro__[1].__name__
    fields = CATALOG[name]["fields"]
    lines = [f"class {name}({base}):"]

    params = []
    for fname, field in fields.items():
        if field.get("kind") == "vector":
            optional = " | None" if field.get("default") is None else ""
            lines.append("    @property")
            lines.append(f"    def {fname}(self) -> tuple[float, ...]{optional}: ...")
            lines.append(f"    @{fname}.setter")
            lines.append(
                f"    def {fname}(self, value: Sequence[float]{optional}) -> None: ..."
            )
            params.append(f"{fname}: Sequence[float]{optional} = ...")
        else:
            annotation = field_annotation(fname, field)
            lines.append(f"    {fname}: {annotation}")
            params.append(f"{fname}: {annotation} = ...")

    joined = ", ".join([*params, "**kwargs: Any"])
    lines.append(f"    def __init__(self, {joined}) -> None: ...")
    return lines


def emit_handwritten_class(name, cls):
    base = cls.__mro__[1].__name__
    lines = [f"class {name}({base}):"]
    for attr_name, attr in vars(cls).items():
        if isinstance(attr, property) and not attr_name.startswith("_"):
            lines.append(f"    {attr_name}: Any")

    parts = []
    for pname, param in list(inspect.signature(cls.__init__).parameters.items())[1:]:
        if param.kind == inspect.Parameter.VAR_KEYWORD:
            parts.append(f"**{pname}: Any")
        elif param.default is inspect.Parameter.empty:
            parts.append(f"{pname}: Any")
        else:
            parts.append(f"{pname}: Any = ...")
    lines.append(f"    def __init__(self, {', '.join(parts)}) -> None: ...")
    return lines


def generate(module):
    body = []
    aliases = []
    emitted = set()
    for name in module.__all__:
        obj = getattr(module, name)
        if not isinstance(obj, type):
            if isinstance(obj, dict):
                body.append(f"{name}: dict[str, str]")
                body.append("")
            continue
        if obj.__name__ != name and obj.__name__ in emitted:
            aliases.append(f"{name} = {obj.__name__}")
            continue
        emitted.add(name)
        emitter = emit_catalog_class if name in CATALOG else emit_handwritten_class
        body.extend(emitter(name, obj))
        body.append("")

    text = "\n".join([*body, *aliases]) + "\n"

    imports = ['"""Generated by scripts/generate_stubs.py — do not edit."""', ""]
    if "Sequence[" in text:
        imports.append("from collections.abc import Sequence")
    imports.append("from typing import Any")
    imports.append("")
    for base_name in ("ThreeJSBase", "Object3D"):
        if f"({base_name})" in text:
            imports.append(f"from .base import {base_name}")
    imports.append("")

    return "\n".join(imports) + "\n" + text


def main():
    paths = []
    for module in MODULES:
        stem = module.__name__.rsplit(".", 1)[-1]
        path = CORE_DIR / f"{stem}.pyi"
        path.write_text(generate(module))
        paths.append(str(path))
    subprocess.run(
        [sys.executable, "-m", "ruff", "format", "--quiet", *paths], check=True
    )
    subprocess.run(
        [sys.executable, "-m", "ruff", "check", "--fix", "--quiet", *paths],
        check=False,
    )
    print(f"wrote {len(paths)} stubs")


if __name__ == "__main__":
    main()
